---
title: "dominant genus and phylum"
author: "xyz"
date: "2021/8/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(dplyr)
```

# Genus

```{r}
otu <- read.csv("../table/OTUByNaive_bayesSortByOneMore.csv")
# 7246
nrow(otu)
meta <- read.csv("../data/metadata2.csv")
meta$Treatment[meta$Treatment=="CK"] <- "Wet"
meta$Time<-rep(rep(c("F1","D1","F2", "D2", "F3", "D3", "F4"),each=3),2)

DNA<-meta$ID[meta$Nucleotide=="DNA"]
# 6649
sum(rowSums(otu[, DNA])>0)
RNA<-meta$ID[meta$Nucleotide=="RNA"]
# 3349
sum(rowSums(otu[, RNA])>0)

DNA<-meta$ID[meta$Nucleotide=="DNA"]
DNA<-rowSums(otu[, DNA])
DNA<-DNA/sum(DNA)*100
# 384
(domainDNA<-sum(DNA>0.05 & otu$Kingdom!="Unassigned"))
domainDNAid<-otu$OTU.ID[DNA>0.05 & otu$Kingdom!="Unassigned"]
RNA<-meta$ID[meta$Nucleotide=="RNA"]
RNA<-rowSums(otu[, RNA])
RNA<-RNA/sum(RNA)*100
# 371
(domainRNA<-sum(RNA>0.05 & otu$Kingdom!="Unassigned"))
domainRNAid<-otu$OTU.ID[RNA>0.05 & otu$Kingdom!="Unassigned"]

DNA<-meta$ID[meta$Nucleotide=="DNA"]
# 5.781391%
domainDNA/sum(rowSums(otu[otu$Kingdom!="Unassigned", DNA])>0)*100
RNA<-meta$ID[meta$Nucleotide=="RNA"]
# 11.12444%
domainRNA/sum(rowSums(otu[otu$Kingdom!="Unassigned", RNA])>0)*100


DNAsintab<-read.csv(
  "../table/DNA otu with significant different abundance2.csv",
  header = T,
  row.names = 1
)
# 35
nrow(DNAsintab)
RNAsintab<-read.csv(
  "../table/RNA otu with significant different abundance2.csv",
  header = T,
  row.names = 1
)
# 58
nrow(RNAsintab)

# 21
sum(rownames(DNAsintab) %in% domainDNAid)
# 36
sum(rownames(RNAsintab) %in% domainRNAid)

DNA<-meta$ID[meta$Nucleotide=="DNA"]
genusDNA<-otu[rowSums(otu[, DNA])>1 & !is.na(otu$Genus),]
# 0.5493562%
sum(rownames(DNAsintab) %in% genusDNA$OTU.ID) / nrow(genusDNA) * 100
RNA<-meta$ID[meta$Nucleotide=="RNA"]
genusRNA<-otu[rowSums(otu[, RNA])>1 & !is.na(otu$Genus),]
# 1.74002%
sum(rownames(RNAsintab) %in% genusRNA$OTU.ID) / nrow(genusRNA) * 100

ID <-
  c(
    "78d5de4558f92e50e8f24220e9c5e1da",
    "89c3b03498a8964a6b8c710f4b6a8799",
    "619d6035eb5a8bc02ca283ad8a922098",
    "78548e0bc766c94cc310b8e18497b7bc"
  )
# 可分类
idOtuDNA<-sum(otu[otu$OTU.ID %in% ID,DNA])
# 0.8297644 %
idOtuDNA/sum(genusDNA[,DNA])*100
idOtuRNA<-sum(otu[otu$OTU.ID %in% ID,RNA])
# 1.095939 %
idOtuRNA/sum(genusRNA[,RNA])*100
# 可分类+不可分类
idOtuDNA<-sum(otu[otu$OTU.ID %in% ID,DNA])
# 0.758769 %
idOtuDNA/sum(otu[,DNA])*100
idOtuRNA<-sum(otu[otu$OTU.ID %in% ID,RNA])
# 0.9960372 %
idOtuRNA/sum(otu[,RNA])*100

```

# phylum

```{r}
otu <- read.csv("../table/OTUByNaive_bayesSortByOneMore.csv")
meta <- read.csv("../data/metadata2.csv")
meta$Treatment[meta$Treatment=="CK"] <- "Wet"
meta$Time<-rep(rep(c("F1","D1","F2", "D2", "F3", "D3", "F4"),each=3),2)

# 63
length(unique(otu$Phylum[!is.na(otu$Phylum)]))

DNA<-meta$ID[meta$Nucleotide=="DNA"]
DNAphylum<-cbind(otu[, DNA],Phylum=otu$Phylum)
DNAphylum<-DNAphylum[rowSums(otu[, DNA])>0,]
# 62
length(unique(DNAphylum$Phylum[!is.na(DNAphylum$Phylum)]))

RNA<-meta$ID[meta$Nucleotide=="RNA"]
RNAphylum<-cbind(otu[, RNA],Phylum=otu$Phylum)
RNAphylum<-RNAphylum[rowSums(otu[, RNA])>0,]
# 50
length(unique(RNAphylum$Phylum[!is.na(RNAphylum$Phylum)]))

phylum<-data.frame(Abundance=rowSums(otu[, 2:43]),Phylum=otu$Phylum)
phylum<-phylum[!is.na(phylum$Phylum),]
phylum<-group_by(phylum,Phylum)
phylum<-summarise(phylum,across(everything(),sum))
phylum$Abundance<-phylum$Abundance/sum(phylum$Abundance)*100
dominantPhylum<-phylum$Phylum[phylum$Abundance>2]

otuRankbyMeta <-
  cbind(OTU.ID = otu$OTU.ID, otu[, meta$ID], Phylum=otu$Phylum)
otuRankbyMeta <- otuRankbyMeta[!is.na(otuRankbyMeta$Phylum),]
phylum <- otuRankbyMeta[, 2:44]
phylum <- group_by(phylum, Phylum)
phylum <- summarise(phylum, across(everything(), sum))

phylumSummary <-
  cbind.data.frame(Nucleotide = meta$Nucleotide,
                   Time = meta$Time,
                   t(phylum[, 2:43]))
phylumSummary <- group_by(phylumSummary, Nucleotide, Time)
phylumSummary <- summarise(phylumSummary, across(everything(), sum))
colnames(phylumSummary)[-1:-2] <- phylum$Phylum
phylumInEachTreat<-colSums(phylumSummary[,-1:-2]>0)==nrow(phylumSummary)
phylumInEachTreat<-colnames(phylumSummary[,-1:-2])[phylumInEachTreat]
# 8
length(intersect(dominantPhylum,phylumInEachTreat))
```

