---
title: "Manhattan plot"
author: "xyz"
date: "2021/8/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("phyloseq")
library("DESeq2")
library("ggplot2")
library("dplyr")
library(stringr)
library(patchwork)
```

# package phylo object

```{r}
otu <- read.csv("../table/OTUByNaive_bayesSortByOneMore.csv")
meta <- read.csv("../data/metadata2.csv")
meta$Treatment[meta$Treatment=="CK"] <- "Wet" 

otu_dna <- otu[, 2:43]
rownames(otu_dna) <- otu$OTU.ID
tax_dna <- otu[, c(44:50)]
rownames(tax_dna) <- otu$OTU.ID
treat_dna <- meta
rownames(treat_dna) <- meta$ID

otus = as.matrix(otu_dna)
taxa = as.matrix(tax_dna)
sampledata = treat_dna

OTU = otu_table(otus, taxa_are_rows = TRUE)
# Filter the number of OTU occurrences in the sample
OTU1 <- filter_taxa(OTU, function(x)
  sum(x > 0) > 1, TRUE)
# Filter the total OTU is less than 10
OTU2 <- prune_taxa(taxa_sums(OTU1) > 9, OTU1)
# rarefy
OTU <- rarefy_even_depth(
  OTU2,
  sample.size = min(sample_sums(OTU2)),
  rngseed = 9527,
  replace = TRUE,
  trimOTUs = TRUE,
  verbose = TRUE
)

TAX = tax_table(taxa)
sampledata = sample_data(sampledata)
phyloseqobj = phyloseq(OTU, TAX)
physeq1 = merge_phyloseq(phyloseqobj, sampledata)
physeq1
```

# abundance difference

```{r}
diagdds = phyloseq_to_deseq2(physeq1, ~ Treatment)
diagdds = DESeq(diagdds, test = "Wald", fitType = "parametric")

res = results(diagdds, cooksCutoff = FALSE)
alpha = 0.01 # Also available 0.05
sigtab = res[which(res$padj < alpha),]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(physeq1)[rownames(sigtab),], "matrix"))
write.csv(sigtab, "../table/otu with significant different abundance.csv")

# Manhattan plot
sigtab = read.csv(
  "../table/otu with significant different abundance.csv",
  header = T,
  row.names = 1
)
sigtab$neglog10p = -log10(sigtab$padj)
sigtab$otu = rownames(sigtab)
sigtab = arrange(sigtab, Phylum, Class, Order, Family, Genus)
sigtab$otu = factor(sigtab$otu, levels = sigtab$otu)
sigtab$num = 1:dim(sigtab)[1]
sigtab[which(sigtab$log2FoldChange < -1 &
               sigtab$padj < 0.05), 'level'] <- 'Depleted'
sigtab[which(sigtab$log2FoldChange > 1 &
               sigtab$padj < 0.05), 'level'] <- 'Enriched'
sigtab[is.na(sigtab)] <- c("no sig")
p = ggplot(sigtab,
           aes(
             x = num,
             y = neglog10p,
             color = Phylum,
             size = log2FoldChange,
             shape = level
           )) +
  geom_point(alpha = .7) +
  scale_shape_manual(values = c(25, 17, 20)) +
  scale_size(breaks = c(5, 10, 15)) +
  theme(legend.position = "top") +
  theme(axis.text.x = element_text(
    angle = 45,
    hjust = 1,
    vjust = 1
  )) + theme_classic()

p
```

# DNA

```{r}
DNA <- subset_samples(physeq1, Nucleotide == "DNA")
diagdds = phyloseq_to_deseq2(DNA, ~ Treatment)
diagdds = DESeq(diagdds, test = "Wald", fitType = "parametric")

res = results(diagdds, contrast = c("Treatment", "Wet", "Dry"))
alpha = 0.01 # Also available 0.05
sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"),
               as(tax_table(physeq1)[rownames(sigtab), ], "matrix"))
write.csv(sigtab,
          "../table/DNA otu with significant different abundance.csv")

# Manhattan plot
sigtab = read.csv(
  "../table/DNA otu with significant different abundance.csv",
  header = T,
  row.names = 1
)
sigtab$neglog10p = -log10(sigtab$padj)
sigtab$otu = rownames(sigtab)
sigtab = arrange(sigtab, Phylum, Class, Order, Family, Genus)
sigtab$otu = factor(sigtab$otu, levels = sigtab$otu)
sigtab$num = 1:dim(sigtab)[1]
sigtab[which(sigtab$log2FoldChange < -1 &
               sigtab$padj <= 0.05), 'level'] <- 'Depleted'
sigtab[which(sigtab$log2FoldChange > 1 &
               sigtab$padj <= 0.05), 'level'] <- 'Enriched'
sigtab <- sigtab[!is.na(sigtab$level), ]

topPhylum <- sort(table(sigtab$Phylum), decreasing = T)
topPhylum <- topPhylum[topPhylum >= 2]
topGenus <- sort(table(sigtab$Genus), decreasing = T)
drawDf <- sigtab
drawDf$Phylum[!(drawDf$Phylum %in% names(topPhylum))] <- "Others"
drawDf$Phylum <- str_remove(drawDf$Phylum, "p__")
drawDf$Genus[!(drawDf$Genus %in% names(topGenus))] <- "Others"
drawDf$Genus <- str_remove(drawDf$Genus, "g__")
drawDf <- arrange(drawDf, Phylum, Class, Order, Family, Genus)
drawDf$num <- 1:nrow(drawDf)

p <- ggplot(drawDf,
            aes(
              x = num,
              y = neglog10p,
              fill = Phylum,
              color = Phylum,
              size = abs(log2FoldChange),
              shape = level
            )) +
  geom_point(alpha = .7) +
  scale_x_continuous(
    breaks = 1:nrow(drawDf),
    labels = drawDf$Genus,
    name = "Genus"
  ) +
  ylab(expression(-log[10](FDR))) +
  # change legend size
  guides(fill = guide_legend(override.aes = list(size = 5)),
         shape = guide_legend(override.aes = list(size = 4))) +
  # change legend tittle
  scale_size_continuous(name = expression(log[2](FC)), breaks = c(2, 4, 6)) +
  scale_shape_manual(name = "Level",values = c(25, 24)) +
  # remove background
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    ),
    axis.text.x = element_text(
      angle = -90,
      vjust = 0.5,
      hjust = 0.01
    ),
    legend.key = element_blank(),
  )

p + ggsave("../figure/DNA Manhattan plot.pdf",
           width = 18,
           height = 8)
pDNA <- p
```

# RNA 

```{r}
RNA <- subset_samples(physeq1, Nucleotide == "RNA")
diagdds = phyloseq_to_deseq2(RNA, ~ Treatment)
diagdds = DESeq(diagdds, test = "Wald", fitType = "parametric")

res = results(diagdds, contrast = c("Treatment", "Wet", "Dry"))
alpha = 0.01 # Also available 0.05
sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"),
               as(tax_table(physeq1)[rownames(sigtab), ], "matrix"))
write.csv(sigtab,
          "../table/RNA otu with significant different abundance.csv")

# Manhattan plot
sigtab = read.csv(
  "../table/RNA otu with significant different abundance.csv",
  header = T,
  row.names = 1
)
sigtab$neglog10p = -log10(sigtab$padj)
sigtab$otu = rownames(sigtab)
sigtab = arrange(sigtab, Phylum, Class, Order, Family, Genus)
sigtab$otu = factor(sigtab$otu, levels = sigtab$otu)
sigtab$num = 1:dim(sigtab)[1]
sigtab[which(sigtab$log2FoldChange < -1 &
               sigtab$padj <= 0.05), 'level'] <- 'Depleted'
sigtab[which(sigtab$log2FoldChange > 1 &
               sigtab$padj <= 0.05), 'level'] <- 'Enriched'
sigtab <- sigtab[!is.na(sigtab$level), ]

topPhylum <- sort(table(sigtab$Phylum), decreasing = T)
topPhylum <- topPhylum[topPhylum >= 2]
topGenus <- sort(table(sigtab$Genus), decreasing = T)
drawDf <- sigtab
drawDf$Phylum[!(drawDf$Phylum %in% names(topPhylum))] <- "Others"
drawDf$Phylum <- str_remove(drawDf$Phylum, "p__")
drawDf$Genus[!(drawDf$Genus %in% names(topGenus))] <- "Others"
drawDf$Genus <- str_remove(drawDf$Genus, "g__")
drawDf <- arrange(drawDf, Phylum, Class, Order, Family, Genus)
drawDf$num <- 1:nrow(drawDf)

p <- ggplot(drawDf,
            aes(
              x = num,
              y = neglog10p,
              fill = Phylum,
              color = Phylum,
              size = abs(log2FoldChange),
              shape = level
            )) +
  geom_point(alpha = .7) +
  scale_x_continuous(
    breaks = 1:nrow(drawDf),
    labels = drawDf$Genus,
    name = "Genus"
  ) +
  ylab(expression(-log[10](FDR))) +
  guides(fill = guide_legend(override.aes = list(size = 5)),
         shape = guide_legend(override.aes = list(size = 4))) +
  scale_size_continuous(name = expression(log[2](FC)), breaks = c(2, 4, 6)) +
  scale_shape_manual(name = "Level",values = c(25, 24)) +
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    ),
    axis.text.x = element_text(
      angle = -90,
      vjust = 0.5,
      hjust = 0.01
    ),
    legend.key = element_blank(),
  )

p + ggsave("../figure/RNA Manhattan plot.pdf",
           width = 16,
           height = 8)
pRNA <- p
```

# merge

```{r}

(pDNA + ggtitle("DNA")) +
  (pRNA+ggtitle("RNA")) +
  plot_layout(nrow = 2) +
  plot_annotation(tag_levels= 'A')+
  ggsave("../figure/All Wet vs Dry Manhattan plot.pdf",
         width = 12,
         height = 12)
```


